[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
rsv = { path = "../rsv" }
profiles = { path = "../profiles" }
wire = { path = "../wire" }
blake3 = "1"
prost = "0.12"
ucf = { package = "ucf-protocol", path = "../ucf-protocol" }
pvgs_client = { path = "../pvgs_client" }
