[package]
name = "dbm_0_sn"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[features]
microcircuit-sn = []

[dependencies]
dbm_core = { path = "../dbm_core" }
microcircuit_core = { path = "../microcircuit_core" }
microcircuit_sn_stub = { path = "../microcircuit_sn_stub" }
