[package]
name = "scorecards"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
query = { path = "../query" }
pvgs = { path = "../pvgs" }

[dev-dependencies]
assets = { path = "../assets" }
