[package]
name = "biophys_channels"
version = "0.1.0"
edition = "2021"

[features]
biophys = []
biophys-l4 = ["biophys"]
biophys-l4-synapses = ["biophys-l4"]
biophys-l4-ca = ["biophys-l4"]

[dependencies]
