[package]
name = "biophys_assets"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1"
ucf = { package = "ucf-protocol", path = "../../ucf-protocol" }

[dev-dependencies]

[features]
biophys-l4-morphology-multi = []
