[package]
name = "profiles"
version = "0.1.0"
edition = "2021"

[dependencies]
rsv = { path = "../rsv" }
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
ucf = { package = "ucf-protocol", path = "../ucf-protocol" }
