[package]
name = "microcircuit_sc_attractor"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
dbm_core = { path = "../dbm_core" }
microcircuit_core = { path = "../microcircuit_core" }
microcircuit_sc_stub = { path = "../microcircuit_sc_stub" }
