[package]
name = "wire"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
serde = { workspace = true }
thiserror = { workspace = true }
ucf = { package = "ucf-protocol", path = "../ucf-protocol" }
