[package]
name = "biophys_morphology"
version = "0.1.0"
edition = "2021"

[features]
biophys = []
biophys-l4 = ["biophys"]
biophys-l4-synapses = ["biophys-l4"]
biophys-l4-morphology-multi = ["biophys-l4"]

[dependencies]
biophys_core = { path = "../biophys_core" }
