[package]
name = "pvgs"
version = "0.1.0"
edition = "2021"

[dependencies]
assets = { path = "../assets" }
blake3 = "1"
thiserror = { workspace = true }
ucf = { package = "ucf-protocol", path = "../../ucf-protocol" }
